version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    restart: always
    ports:
      - "8123:8123"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Los_Angeles  # Set your timezone here

volumes:
  portainer_data:
  homeassistant_config:
